Port page not able to load sometimes-Fixed
Port page not able to load sometimes
Issue:
TypeError: self.deviceOwner is not a function
-Placed the function return as inline.
So it will be not be looking for that variable.

Change-Id: I23810689e0d7443960c6eee5115309b48f04427b
Closes-Bug: #1542295