Error: 413 Request Entity Too Large" when creating SI
Removed unwanted objects before sending to WebServer from Web Client which was
consisting all the Svc Template details which was causing to send huge data to
API Server.
Added the vmStatus fallback in exception case where we do not get the VM details
in nova.

Change-Id: I05202ca78c7f2c098617f04e94a6829573e0f324
Closes-Bug: #1733130